"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Search, UserPlus, UserMinus, MessageCircle, Check, X, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
type Profile={id:string;username:string;bio:string;avatar_url:string;last_seen:string};
type Req={id:string;sender_id:string;receiver_id:string;status:string;sender?:Profile;receiver?:Profile};
export function MobileNetwork(){
 const [tab,setTab]=useState("Friends"),[user,setUser]=useState(""),[friends,setFriends]=useState<Profile[]>([]),[requests,setRequests]=useState<Req[]>([]),[sent,setSent]=useState<Req[]>([]),[q,setQ]=useState(""),[people,setPeople]=useState<Profile[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 async function load(){const s=createClient();const {data:{user:u}}=await s.auth.getUser();if(!u){window.location.href="/login";return}setUser(u.id);const {data:f}=await s.from("friendships").select("friend_id").eq("user_id",u.id);const ids=(f??[]).map(x=>x.friend_id);setFriends(ids.length?(await s.from("profiles").select("id,username,bio,avatar_url,last_seen").in("id",ids)).data??[]:[]);const {data:r}=await s.from("friend_requests").select("id,sender_id,receiver_id,status").eq("receiver_id",u.id).eq("status","pending");setRequests(r?.length?(await s.from("profiles").select("id,username,bio,avatar_url,last_seen").in("id",r.map(x=>x.sender_id))).data?.map(p=>({...r.find(x=>x.sender_id===p.id),sender:p} as Req))??[]:[]);const {data:sr}=await s.from("friend_requests").select("id,sender_id,receiver_id,status").eq("sender_id",u.id).eq("status","pending");setSent(sr?.length?(await s.from("profiles").select("id,username,bio,avatar_url,last_seen").in("id",sr.map(x=>x.receiver_id))).data?.map(p=>({...sr.find(x=>x.receiver_id===p.id),receiver:p} as Req))??[]:[]);setLoading(false)}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),5000);return()=>clearInterval(t)},[]);
 async function search(v:string){setQ(v);if(!v.trim()){setPeople([]);return}const {data}=await createClient().from("profiles").select("id,username,bio,avatar_url,last_seen").ilike("username","%"+v.trim().toLowerCase()+"%").neq("id",user).limit(8);setPeople(data??[])}
 async function add(p:Profile){const {data,error}=await createClient().rpc("send_friend_request",{receiver_user:p.id});if(error)setNotice(error.message);else if(data)setNotice("REQUEST SENT TO @"+p.username);void load()}
 async function respond(r:Req,ok:boolean){const {error}=await createClient().rpc(ok?"accept_friend_request":"reject_friend_request",{request_id:r.id});if(error)setNotice(error.message);void load()}
 async function remove(p:Profile){const {error}=await createClient().rpc("remove_friend",{friend_user:p.id});if(error)setNotice(error.message);void load()}
 if(loading)return <main className="mobile-page"><div className="mobile-page-title"><span>SOCIAL / NETWORK</span><h1>PEOPLE.</h1></div><div className="mobile-loading">LOADING...</div></main>;
 return <main className="mobile-page"><div className="mobile-page-title"><span>SOCIAL / NETWORK</span><h1>PEOPLE.</h1></div><div className="mobile-network-search"><Search size={15}/><input value={q} onChange={e=>void search(e.target.value)} placeholder="SEARCH USERNAME"/></div>{people.length>0&&<div className="mobile-search-results">{people.map(p=><div className="mobile-person" key={p.id}><Link href={"/profile/"+p.username} className="mobile-user">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span>{p.username[0]}</span>}<b>@{p.username}</b></Link><button onClick={()=>void add(p)}><UserPlus size={15}/></button></div>)}</div>}<div className="mobile-tabs mobile-network-tabs">{["Friends","Requests","Discover"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{notice&&<div className="mobile-error">{notice}</div>}{tab==="Friends"&&<div className="mobile-list">{friends.length?friends.map(f=><div className="mobile-row" key={f.id}><Link href={"/profile/"+f.username} className="mobile-user">{f.avatar_url?<img src={f.avatar_url} alt=""/>:<span>{f.username[0]}</span>}<b>@{f.username}</b></Link><Link href={"/messages/"+f.username} className="mobile-icon"><MessageCircle size={16}/></Link><button className="mobile-icon" onClick={()=>void remove(f)}><UserMinus size={16}/></button></div>):<div className="mobile-empty">NO FRIENDS YET.<small>FIND PEOPLE ABOVE.</small></div>}</div>}{tab==="Requests"&&<div className="mobile-list">{requests.length?requests.map(r=><div className="mobile-row" key={r.id}><Link href={"/profile/"+r.sender?.username} className="mobile-user">{r.sender?.avatar_url?<img src={r.sender.avatar_url} alt=""/>:<span>{r.sender?.username?.[0]}</span>}<b>@{r.sender?.username}</b></Link><button className="mobile-icon" onClick={()=>void respond(r,true)}><Check size={16}/></button><button className="mobile-icon" onClick={()=>void respond(r,false)}><X size={16}/></button></div>):<div className="mobile-empty">NO REQUESTS.<small>YOU'RE ALL CAUGHT UP.</small></div>}</div>}{tab==="Discover"&&<div className="mobile-empty">SEARCH FOR PEOPLE.<small>TYPE A USERNAME ABOVE.</small></div>}</main>}
