"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { Bell,Check,Heart,MessageCircle,MessageSquare,UserPlus,X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
export function MobileNotifications(){const [open,setOpen]=useState(false),[items,setItems]=useState<any[]>([]);
async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {data:r}=await s.from("friend_requests").select("id,sender_id,created_at").eq("receiver_id",user.id).eq("status","pending").order("created_at",{ascending:false});const {data:n}=await s.from("notifications").select("id,type,sender_id,created_at").eq("user_id",user.id).is("read_at",null).order("created_at",{ascending:false}).limit(20);const ids=[...(r??[]).map(x=>x.sender_id),...(n??[]).map(x=>x.sender_id)];const {data:p}=ids.length?await s.from("profiles").select("id,username,avatar_url").in("id",ids):{data:[]};setItems([...(r??[]).map(x=>({id:"f"+x.id,kind:"friend",username:p?.find(y=>y.id===x.sender_id)?.username})),...(n??[]).map(x=>({id:x.id,kind:x.type,username:p?.find(y=>y.id===x.sender_id)?.username}))])}
useEffect(()=>{void load();const t=setInterval(()=>void load(),5000);return()=>clearInterval(t)},[]);
async function read(id:string){await createClient().from("notifications").update({read_at:new Date().toISOString()}).eq("id",id);void load()}
function icon(k:string){if(k==="post_like")return <Heart size={14}/>;if(k==="post_comment")return <MessageCircle size={14}/>;if(k==="friend_accepted")return <Check size={14}/>;if(k==="message")return <MessageSquare size={14}/>;return <UserPlus size={14}/>}
function text(k:string){if(k==="friend")return"Sent you a friend request";if(k==="post_like")return"Liked your post";if(k==="post_comment")return"Left a comment on your post";if(k==="friend_accepted")return"Accepted your friend request";return"Sent you a message"}
return <><button className="mobile-notification-button" onClick={()=>setOpen(true)} aria-label="Notifications"><Bell size={17}/>{items.length>0&&<span>{items.length>9?"9+":items.length}</span>}</button>{open&&<div className="mobile-notification-overlay"><div className="mobile-overlay-header"><button onClick={()=>setOpen(false)} aria-label="Close"><X size={19}/></button><span>NOTIFICATIONS</span><span className="mobile-overlay-spacer"/></div><div>{items.length?items.map(x=><Link key={x.id} href={x.kind==="message"?"/messages/"+x.username:x.kind==="post_like"||x.kind==="post_comment"?"/":"/profile/"+x.username} onClick={()=>x.kind!=="friend"&&void read(x.id)} className="mobile-notification-row">{icon(x.kind)}<span><b>@{x.username||"user"}</b><small>{text(x.kind)}</small></span></Link>):<div className="mobile-empty">NOTHING NEW.</div>}</div></div>}</>}
