"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { LogOut,Save,ImagePlus,UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
export function MobileProfile(){const [email,setEmail]=useState(""),[p,setP]=useState<any>({username:"",bio:"",avatar_url:"",banner_url:"",online:true}),[id,setId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return}setId(user.id);setEmail(user.email??"");const {data}=await s.from("profiles").select("username,bio,avatar_url,banner_url,show_online").eq("id",user.id).maybeSingle();setP({username:data?.username??user.user_metadata?.username??"",bio:data?.bio??"",avatar_url:data?.avatar_url??"",banner_url:data?.banner_url??"",online:data?.show_online??true});setLoading(false)})()},[]);
async function save(){setSaving(true);const s=createClient(),username=p.username.trim().toLowerCase();const {error}=await s.from("profiles").upsert({id,username,bio:p.bio.trim(),avatar_url:p.avatar_url,banner_url:p.banner_url,show_online:p.online});setMessage(error?.message??"PROFILE SAVED.");setSaving(false)}
async function logout(){await createClient().auth.signOut();window.location.href="/"}
if(loading)return <main className="mobile-page"><div className="mobile-loading">LOADING...</div></main>;
return <main className="mobile-page"><div className="mobile-page-title"><span>ACCOUNT</span><h1>PROFILE.</h1></div><section className="mobile-profile-card"><div className="mobile-banner">{p.banner_url&&<img src={p.banner_url} alt=""/>}</div><div className="mobile-profile-head"><div className="mobile-profile-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<UserRound size={28}/>}</div><div><b>@{p.username}</b><small>{email}</small></div></div></section><div className="mobile-form"><label>USERNAME<input value={p.username} onChange={e=>setP({...p,username:e.target.value.replace(/\s/g,"").slice(0,24)})}/></label><label>BIO<textarea value={p.bio} maxLength={160} onChange={e=>setP({...p,bio:e.target.value.slice(0,160)})}/><small>{p.bio.length}/160</small></label><label className="mobile-toggle">ONLINE<input type="checkbox" checked={p.online} onChange={e=>setP({...p,online:e.target.checked})}/></label>{message&&<p className="mobile-error">{message}</p>}<button onClick={save} disabled={saving}><Save size={14}/>{saving?"SAVING...":"SAVE PROFILE"}</button><Link href={"/profile/"+p.username}>VIEW PUBLIC PROFILE</Link><button className="mobile-outline" onClick={logout}><LogOut size={14}/>LOG OUT</button></div></main>}